/*
Copyright 2026 The DTorch Authors. All rights reserved.

Author: Tingkuan Pei(contact: peitingkuan@163.com)
*/

#pragma once

#include <condition_variable>
#include <mutex>
#include <string>
#include <vector>

#include "dtorch/core/distributed/cluster_info.h"
#include "dtorch/core/distributed/process_heart_beat.h"
#include "dtorch/external/rpc/main_node_interface.h"
#include "dtorch/external/rpc/worker_node_interface.h"

namespace dtorch {
namespace api {
namespace cpp {
struct GraphOption;
}  // namespace cpp
}  // namespace api
namespace core {
namespace distributed {

class MainNode {
public:
    static std::string GetRefMainNodeAddress();

    static void SetRefMainNodeAddress(const std::string& address);

    // Environment variable names that should be synced to WorkerNodes
    static const std::vector<std::string>& GetEnvVarsToSync();

public:
    MainNode(const std::string& mainNodeAddress);

    ~MainNode();

    bool WaitClusterReady(size_t numNodes, double timeoutSecond);

    int64_t NumNodeInCluster() const;

    const std::string& GetMainNodeAddress() const;

    const std::string& GetMainProcessHeartBeatAddress() const;

    // Register a new graph cluster-wide: records graphId and fans out to all WorkerNodes so
    // each spawns its RemoteRunner subprocesses for this graph (joining the broadcast fabric
    // at publisherAddress/pushPullAddress). supportedDevicesForNodes[i] is the device set for
    // node i (node 0 is the MainNode); each worker receives its own slice. The addresses are
    // per-graph (generated by Graph::Impl) since each graph owns its own publisher/puller.
    void CreateGraph(uint64_t graphId, const api::cpp::GraphOption& graphOption,
                     const std::vector<RunnerSupportedDevices>& supportedDevicesForNodes,
                     const std::string& publisherAddress, const std::string& pushPullAddress);

    void DestroyGraph(uint64_t graphId);

    void AddWorkerNode(const std::string& workerNodeAddress, int gpuCount);

private:
    void AddNodeImp(const NodeInfo& nodeInfo);

private:
    static std::string kRefMainNodeAddress;

private:
    using MainNodeServer = external::rpc::MainNodeServer;
    using WorkerNodeClient = external::rpc::WorkerNodeClient;

    std::unique_ptr<MainNodeServer> mMainNodeServer;
    std::vector<WorkerNodeClient> mWorkerNodeClients;
    std::unique_ptr<MainProcessHeartBeat> mMainProcessHeartBeat;
    mutable std::mutex mMutex;
    std::condition_variable mCv;
    std::unordered_set<uint64_t> mGraphIdSet;
};

}  // namespace distributed
}  // namespace core
}  // namespace dtorch
